### PR TITLE
First checkin of Open Source CLM E1

### PR DESCRIPTION
**Pull request by SgrAlpha**
The first commit of Open Source CLM E1

### CODE REVIEW

**Comment by rjminsha** [comment]
We could perhaps change the structure to 
automation 
automation/clm-e1
automation/clm-e1/src
automation/clm-e1/dist

**Comment by rjminsha** [comment]
I did not have permission to make changes on your repository to update the pull request which surprised me given I am listed as a contributor on your repository (assume that came directly from the fork).

**Comment by rjminsha** [comment]
I don't think that we can include the rpms in the repository.  These most likely have different license conditions than that of the distribution.  

This may need to be handled by a basic build script ... README.md instructs them to download the rpms to downloads folder, build script copies to the correct place, clean removes and copies back to download.  

Also not sure we need multiple versions in the dist.

**Comment by SgrAlpha** [comment]
This reminds me another thing, for now I have a version string(sub folder) under each component, which makes the folder structure matches the UCD artifacts repository, should I replace that with git tag?

Maybe we can provide a global build scripts for users to help them download rpms, and organize the files like UCD repository and create versions in UCD.

What do you think?

**Comment by rjminsha** [comment]
I'd say that removing versioning from the source structure, then providing build scripts and perhaps testing with drone.io or another build service is a good way to go.  This is based on the idea that we don't want to maintain too many branches of the code for different versions but simply support a 'latest' or close to set of automation. 

I'm very open to discussion on this.  Perhaps we let it play out with the current structure, put in the build scripts and downloads folder, look at hte licensing of each of the rpms and then discuss.

**Comment by SgrAlpha** [comment]
Here are the licenses:

pixman-0.26.2-5.1.el6_5.x86_64.rpm MIT
xorg-x11-server-common-1.13.0-23.1.el6_5.x86_64.rpm MIT
xorg-x11-server-Xorg-1.13.0-23.1.el6_5.x86_64.rpm MIT
xorg-x11-server-Xvfb-1.13.0-23.1.el6_5.x86_64.rpm MIT and GPLv2

I got these info by using rpm -qpil <rpm file>

I think we are good with MIT license, am I correct?

**Pull request merged**
